#!/usr/bin/env python3
"""
lift_all.py - lift every code segment of IR32.DLL and emit the glue.

Running lift_ir32.py by hand once per segment stops being reasonable at 40 of
them, and the runtime needs to know which ones exist: each lifted segment
publishes an entry table, and something has to declare and register them all.
That list is generated rather than maintained, because a segment that is lifted
but never registered fails as "no lifted entry for 000E:0000" at run time,
which is a long way from the cause.

Segments with no `ret` anywhere are skipped. They are data - see the README -
and lifting one produces a single enormous function that looks like the best
result in the table.

    py lift_all.py <IR32.DLL> -o <outdir>
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ne_file")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--pcrecomp", default=r"G:\recomp\pc\tools")
    a = ap.parse_args()

    sys.path.insert(0, os.path.join(a.pcrecomp, "tools", "ne"))
    sys.path.insert(0, os.path.join(a.pcrecomp, "tools", "disasm"))
    import ne_parse

    ne = ne_parse.parse_ne(a.ne_file)
    os.makedirs(a.out, exist_ok=True)

    lifted16, lifted32, skipped = [], [], []
    for seg in ne.code_segments:
        if not seg.data:
            continue
        idx = seg.index
        out = os.path.join(a.out, "ir32_seg%d.c" % idx)
        r = subprocess.run(
            [sys.executable, os.path.join(HERE, "lift_ir32.py"), a.ne_file,
             "--seg", str(idx), "-o", out, "--pcrecomp", a.pcrecomp],
            capture_output=True, text=True)
        log = r.stdout + r.stderr
        if r.returncode != 0:
            print("seg %-3d FAILED\n%s" % (idx, log))
            return 1
        if "WARNING: not one return" in log:
            skipped.append(idx)
            os.remove(out)
            print("seg %-3d skipped: data, not code" % idx)
            continue
        is32 = "is 32-bit" in log
        (lifted32 if is32 else lifted16).append(idx)
        cov = [l for l in log.splitlines() if "covering" in l]
        print("seg %-3d %-7s %s" % (idx, "32-bit" if is32 else "16-bit",
                                    cov[0] if cov else ""))

    hdr = os.path.join(a.out, "ir32_segs.h")
    with open(hdr, "w") as f:
        f.write("/* GENERATED by lift_all.py - which segments were lifted.\n"
                " *\n"
                " * Declaring and registering these by hand is the kind of list\n"
                " * that goes stale silently: a segment lifted but not registered\n"
                " * shows up as `no lifted entry for 000E:0000` at run time, a long\n"
                " * way from the cause.\n"
                " */\n#ifndef IR32_SEGS_H\n#define IR32_SEGS_H\n\n")
        f.write("#define IR32_SEGS16(X) \\\n")
        f.write(" \\\n".join("    X(%d)" % i for i in lifted16) or "    /* none */")
        f.write("\n\n#define IR32_SEGS32(X) \\\n")
        f.write(" \\\n".join("    X(%d)" % i for i in lifted32) or "    /* none */")
        f.write("\n\n#endif\n")

    print("\nlifted %d 16-bit and %d 32-bit segments; skipped %d as data (%s)"
          % (len(lifted16), len(lifted32), len(skipped),
             ", ".join(str(x) for x in skipped) or "-"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
