/* AUTO-GENERATED by lift.py - do not edit */
#include "cpu.h"

void L_00401D10(CPU *c)
{
    push32(c, 0x7F00u);                                          /* 00401D10: push 0x7f00 */
    push32(c, 0x0u);                                             /* 00401D15: push 0 */
    push32(c, 0x00401D1Du); dispatch(c, rd32((GVA(0x0058DC80)))); /* 00401D17: call dword ptr [0x58dc80] */
    push32(c, c->eax);                                           /* 00401D1D: push eax */
    push32(c, 0x00401D24u); dispatch(c, rd32((GVA(0x0058DC84)))); /* 00401D1E: call dword ptr [0x58dc84] */
    c->eax = (uint32_t)(0x1u);                                   /* 00401D24: mov eax, 1 */
    c->esp += 16; return;                                        /* 00401D29: ret 0xc */
}
