"""Find a pure self-contained lifted->lifted chain in ENC97:
   caller A direct-calls leaf B; neither references imports; B has no calls.
   Prints candidates with arg-count guesses (from `ret N`) for differential testing.
"""
import struct, sys
from capstone import Cs, CS_ARCH_X86, CS_MODE_32, CS_OP_MEM, CS_AC_WRITE

import os
# This repo first, then the path it was originally written against.
_here = os.path.dirname(os.path.abspath(__file__))
EXE = next((q for q in [os.environ.get("ENC97_EXE"),
                        os.path.join(_here, "..", "..", "analysis", "ENC97.EXE"),
                        r"C:\encarta\analysis\ENC97.EXE"]
            if q and os.path.exists(q)), None)
FUNCS = next((q for q in [os.environ.get("ENC97_FUNCS"),
                          os.path.join(_here, "funcs.txt"),
                          r"E:\ida\work\enc97\funcs.txt"]
              if q and os.path.exists(q)), None)

f = open(EXE, "rb").read()
pe = struct.unpack_from("<I", f, 0x3c)[0]
nsec = struct.unpack_from("<H", f, pe + 6)[0]
so = pe + 24 + struct.unpack_from("<H", f, pe + 20)[0]
base = struct.unpack_from("<I", f, pe + 24 + 28)[0]
secs = {}
text = None
for i in range(nsec):
    o = so + i * 40
    nm = f[o:o+8].split(b"\0")[0].decode()
    vs, va, rs, pr = struct.unpack_from("<IIII", f, o + 8)
    secs[nm] = (base+va, vs, pr, rs)
    if nm == ".text":
        text = (base+va, vs, pr, rs)

idata_lo = secs[".idata"][0]
idata_hi = idata_lo + secs[".idata"][1]
tlo, tvs, tpr, trs = text
thi = tlo + tvs

funcs = {}
order = []
for line in open(FUNCS):
    parts = line.split()
    if len(parts) >= 3 and parts[0].startswith("0x"):
        a = int(parts[0], 16); sz = int(parts[1]); funcs[a] = sz; order.append(a)

md = Cs(CS_ARCH_X86, CS_MODE_32)
md.detail = True

def code_for(addr, sz):
    off = tpr + (addr - tlo)
    return f[off:off+sz]

def analyze(addr):
    """return (has_call, calls_to[list], touches_import, ret_imm, has_indirect, only_arith)"""
    sz = funcs.get(addr, 0)
    if not sz or addr < tlo or addr+sz > thi:
        return None
    calls = []
    touches_import = False
    has_indirect = False
    writes_mem = False
    has_loop = False
    ret_imm = 0
    insns = list(md.disasm(code_for(addr, sz), addr))
    for ins in insns:
        m = ins.mnemonic
        # any memory store (incl. rep stos/movs) => not safe to fuzz blindly
        if m.startswith(("movs", "stos", "rep")):
            writes_mem = True
        # backward branch within the function => a loop (can hang / unbounded probe)
        if (m == "jmp" or m.startswith("j")) and ins.operands and ins.operands[0].type == 2:
            t = ins.operands[0].imm
            if addr <= t < ins.address:
                has_loop = True
        if m == "call":
            op = ins.operands[0]
            if op.type == 1:  # reg/imm? capstone: 1=reg,2=imm,3=mem
                pass
            if ins.operands[0].type == 2:  # imm direct
                calls.append(ins.operands[0].imm)
            else:
                has_indirect = True
        if m == "jmp":
            if ins.operands and ins.operands[0].type == 2:
                t = ins.operands[0].imm
                if not (addr <= t < addr+sz):
                    calls.append(t)  # tail call
            else:
                has_indirect = True  # jump table / computed jmp -> lift abort()s on default
        if m.startswith("ret"):
            if ins.operands and ins.operands[0].type == 2:
                ret_imm = ins.operands[0].imm
        for op in ins.operands:
            if op.type == CS_OP_MEM:
                disp = op.mem.disp
                if idata_lo <= disp < idata_hi:
                    touches_import = True
                if op.access & CS_AC_WRITE:
                    writes_mem = True
    return (len(calls) > 0, calls, touches_import, ret_imm, has_indirect, insns, writes_mem, has_loop)

# pure leaf: in funcs, no calls, no indirect, no import touch
pure_leaf = set()
for a in funcs:
    r = analyze(a)
    if r and not r[0] and not r[2] and not r[4]:
        pure_leaf.add(a)

print(f"pure leaves: {len(pure_leaf)} of {len(funcs)}", file=sys.stderr)

# emit a header of SAFE pure leaves: no calls/imports/indirect, NO memory writes,
# and NO loop (no backward branch). Such a leaf is bounded straight-line compute:
# it cannot hang, cannot unbounded-probe memory, and a fault can only be a
# catchable read AV. (This also drops CRT helpers like _chkstk/memcpy.)
# ret N => stdcall arg bytes.
safe = [a for a in sorted(pure_leaf) if not analyze(a)[6] and not analyze(a)[7]]
with open("enc97_pure_leaves.h", "w") as h:
    h.write("/* AUTO-GENERATED by find_pure_chain.py: SAFE pure leaves (no calls/imports/writes) */\n")
    h.write("/* L(va, ret_imm_bytes) */\n#define PURE_LEAVES(L) \\\n")
    for a in safe:
        ret_imm = analyze(a)[3]
        h.write(f"    L(0x{a:06x}, {ret_imm}) \\\n")
    h.write("\n")
print(f"[*] wrote enc97_pure_leaves.h ({len(safe)} safe of {len(pure_leaf)} pure leaves)", file=sys.stderr)

# A second, larger set: pure leaves that DO write memory but still have no
# backward branch. Writes were excluded for fear of corruption, and on
# reflection that fear is misplaced - a store through a pointer derived from a
# zeroed register lands near null and raises a catchable access violation, the
# same as the reads these functions already do. What must stay excluded is the
# loop: a backward branch can spin forever or walk memory until it finds
# something, and neither is recoverable.
#
# These are worth more than the no-write set, not less. A function whose only
# observable effect is on memory is invisible to a comparison of eax alone, so
# the sweep for these compares the buffer as well - which is a stronger check
# than the one the 818 get.
def uses_x87(a):
    """Does this function compute with the FPU?

    pcrecomp models the x87 stack as C doubles where the hardware carries
    80-bit extended. On real inputs that costs a few low bits; on the synthetic
    input this sweep uses - pointer bits reinterpreted as doubles - it diverges
    completely, because intermediates that overflow a 64-bit double are
    perfectly representable in 80-bit. sub_50BCD0 lands on negative zero in
    hardware and on a huge value in the model.

    So a float leaf compared on garbage cannot tell a lift bug from the
    modelling limit, and is reported separately rather than as a failure.
    """
    return any(i.mnemonic.startswith("f") and i.mnemonic not in ("fs", "fld_dummy")
               for i in analyze(a)[5])

writers_all = [a for a in sorted(pure_leaf) if analyze(a)[6] and not analyze(a)[7]]
writers = [a for a in writers_all if not uses_x87(a)]
floats = [a for a in writers_all if uses_x87(a)]
with open("enc97_write_leaves.h", "w") as h:
    h.write("/* AUTO-GENERATED by find_pure_chain.py: pure leaves that WRITE\n"
            "   memory but do not loop. Compared on memory as well as eax. */\n")
    h.write("/* L(va, ret_imm_bytes) */\n#define WRITE_LEAVES(L) \\\n")
    for a in writers:
        h.write(f"    L(0x{a:06x}, {analyze(a)[3]}) \\\n")
    h.write("\n")
print(f"[*] wrote enc97_write_leaves.h ({len(writers)} writing leaves; "
      f"{len(floats)} float leaves held back - see uses_x87)", file=sys.stderr)

# find caller A: calls >=1 leaf, ALL its direct calls go to pure_leaf, no import touch, no indirect
cands = []
for a in funcs:
    r = analyze(a)
    if not r: continue
    has_call, calls, imp, ret_imm, indir, insns = r
    if not has_call or imp or indir: continue
    callees = [c for c in calls if c in funcs]
    if not callees: continue
    if all(c in pure_leaf for c in callees) and len(insns) < 60:
        cands.append((a, ret_imm, callees, len(insns)))

cands.sort(key=lambda x: x[3])
print(f"pure caller candidates: {len(cands)}")
for a, ret_imm, callees, ni in cands[:25]:
    print(f"  A=0x{a:x} ret={ret_imm} ninsn={ni} callees={[hex(c) for c in callees]} "
          f"(sizes {[funcs[c] for c in callees]})")
