"""Find a DEEP self-contained pure chain in ENC97: a root function whose entire
transitive direct-call closure stays inside 'pure' functions (no imports, no
indirect calls), spanning multiple levels / several functions. Such a root, run
through the full lifted dispatch table, traverses many lifted functions purely.
"""
import struct, sys
from capstone import Cs, CS_ARCH_X86, CS_MODE_32, CS_OP_MEM

EXE = r"C:\encarta\analysis\ENC97.EXE"
FUNCS = r"E:\ida\work\enc97\funcs.txt"

f = open(EXE, "rb").read()
pe = struct.unpack_from("<I", f, 0x3c)[0]
nsec = struct.unpack_from("<H", f, pe + 6)[0]
so = pe + 24 + struct.unpack_from("<H", f, pe + 20)[0]
base = struct.unpack_from("<I", f, pe + 24 + 28)[0]
secs = {}
for i in range(nsec):
    o = so + i * 40
    nm = f[o:o+8].split(b"\0")[0].decode()
    vs, va, rs, pr = struct.unpack_from("<IIII", f, o + 8)
    secs[nm] = (base + va, vs, pr, rs)
tlo, tvs, tpr, trs = secs[".text"]
thi = tlo + tvs
idata_lo = secs[".idata"][0]; idata_hi = idata_lo + secs[".idata"][1]

funcs = {}
for line in open(FUNCS):
    p = line.split()
    if len(p) >= 3 and p[0].startswith("0x"):
        funcs[int(p[0], 16)] = int(p[1])

md = Cs(CS_ARCH_X86, CS_MODE_32); md.detail = True

info = {}  # addr -> (calls set, touches_import, indirect, ret_imm)
for a, sz in funcs.items():
    if a < tlo or a + sz > thi:
        info[a] = (set(), True, True, 0); continue
    off = tpr + (a - tlo)
    calls = set(); imp = False; indir = False; ret_imm = 0
    for ins in md.disasm(f[off:off+sz], a):
        m = ins.mnemonic
        if m == "call":
            op = ins.operands[0]
            if op.type == 2: calls.add(op.imm)
            else: indir = True
        elif m == "jmp" and ins.operands and ins.operands[0].type == 2:
            t = ins.operands[0].imm
            if not (a <= t < a + sz): calls.add(t)
        elif m.startswith("ret") and ins.operands and ins.operands[0].type == 2:
            ret_imm = ins.operands[0].imm
        for op in ins.operands:
            if op.type == CS_OP_MEM and idata_lo <= op.mem.disp < idata_hi:
                imp = True
    info[a] = (calls, imp, indir, ret_imm)

# pure-closure: a function is "deep-pure" if it + all transitively reachable
# direct callees are in funcs, no imports, no indirect calls.
from functools import lru_cache
memo = {}
def closure(a, stack):
    if a in memo: return memo[a]
    if a not in info: return (False, set())
    calls, imp, indir, _ = info[a]
    if imp or indir:
        memo[a] = (False, set()); return memo[a]
    if a in stack:  # recursion - treat as pure-so-far, closure handled by caller
        return (True, set())
    allset = set()
    ok = True
    for c in calls:
        if c not in funcs:
            ok = False; break
        cok, cset = closure(c, stack | {a})
        if not cok: ok = False; break
        allset |= {c} | cset
    res = (ok, allset)
    if not (a in stack):  # only memoize complete results
        memo[a] = res
    return res

cands = []
for a in funcs:
    calls = info[a][0]
    if not any(c in funcs for c in calls):  # want roots that DO call internally
        continue
    ok, cset = closure(a, set())
    if ok and len(cset) >= 2:
        # depth estimate
        cands.append((a, len(cset), info[a][3], sorted(cset)))

cands.sort(key=lambda x: -x[1])
print(f"deep-pure roots: {len(cands)}")
for a, n, ret_imm, cset in cands[:20]:
    print(f"  root=0x{a:x} closure={n} ret={ret_imm} fns={[hex(x) for x in cset[:8]]}{'...' if n>8 else ''}")

with open("enc97_deep_roots.h", "w") as h:
    h.write("/* AUTO-GENERATED by find_deep_chain.py: self-contained pure roots */\n")
    h.write("/* R(root_va, closure_size, ret_imm) */\n#define DEEP_ROOTS(R) \\\n")
    for a, n, ret_imm, cset in cands:
        h.write(f"    R(0x{a:06x}, {n}, {ret_imm}) \\\n")
    h.write("\n")
print(f"[*] wrote enc97_deep_roots.h ({len(cands)} roots)")
