"""Generate deco32_data.c: the initialized data sections (.rdata/.data/.idata)
of DECO_32.DLL that the lifted decoder reads via GVA(), as a C blob + a loader
that places them at their RVAs in a freshly-allocated 0x11000000 image. This
lets recomp_decode run with NO DLL file at runtime (.text isn't needed — no
original code executes; .bss is zero-filled by VirtualAlloc).

The output is derived from the user's own DECO_32.DLL and is gitignored (like
enc97_full.c) — it is a build artifact, not redistributed.

Usage: py gen_deco_data.py [DECO_32.DLL] [out.c]
"""
import struct, sys

DLL = sys.argv[1] if len(sys.argv) > 1 else r"C:\encarta\analysis\DECO_32.DLL"
OUT = sys.argv[2] if len(sys.argv) > 2 else "deco32_data.c"
import os
# Sections to include. Override via env DECO_SECTIONS (comma list) to minimize.
# Default: ALL sections. .text is required even though no original code runs —
# MSVC 4.x embeds the decoder's jump tables inline in .text, and the lifted
# if-chains read those table entries via GVA() to pick their branch target.
WANT = os.environ.get("DECO_SECTIONS")
WANT = set(WANT.split(",")) if WANT else None   # None => all sections

f = open(DLL, "rb").read()
pe = struct.unpack_from("<I", f, 0x3c)[0]
nsec = struct.unpack_from("<H", f, pe + 6)[0]
base = struct.unpack_from("<I", f, pe + 24 + 28)[0]
imgsz = struct.unpack_from("<I", f, pe + 24 + 56)[0]
soh = struct.unpack_from("<I", f, pe + 24 + 60)[0]
so = pe + 24 + struct.unpack_from("<H", f, pe + 20)[0]

segs = [(0, f[0:soh])]   # PE headers at base+0 (some globals point into them)
for i in range(nsec):
    o = so + i * 40
    nm = f[o:o+8].split(b"\0")[0].decode()
    vs, va, rs, pr = struct.unpack_from("<IIII", f, o + 8)
    if not rs:
        continue
    keep = (nm in WANT) if WANT is not None else True
    if keep:
        segs.append((va, f[pr:pr+rs]))

blob = b"".join(b for _, b in segs)
descr, off = [], 0
for va, b in segs:
    descr.append((va, off, len(b)))
    off += len(b)

with open(OUT, "w") as w:
    w.write("/* AUTO-GENERATED by gen_deco_data.py from DECO_32.DLL - do not edit.\n")
    w.write(" * Initialized data sections (.rdata/.data/.idata) placed at their RVAs\n")
    w.write(" * so the lifted decoder runs with no DLL file. Build artifact (gitignored). */\n")
    w.write("#include <stdint.h>\n#include <string.h>\n\n")
    w.write(f"#define DECO_IMAGE_BASE 0x{base:08x}u\n")
    w.write(f"#define DECO_IMAGE_SIZE 0x{imgsz:08x}u\n\n")
    w.write(f"static const unsigned char DECO_BLOB[{len(blob)}] = {{\n")
    for i in range(0, len(blob), 20):
        w.write("  " + ",".join(str(x) for x in blob[i:i+20]) + ",\n")
    w.write("};\n\n")
    w.write("static const struct { unsigned rva, off, len; } DECO_SEG[] = {\n")
    for va, o2, ln in descr:
        w.write(f"  {{ 0x{va:06x}u, {o2}u, {ln}u }},\n")
    w.write("};\n\n")
    w.write("/* place the initialized data at base+rva (image already zeroed). */\n")
    w.write("void deco_load_data(unsigned char *image_base) {\n")
    w.write("    for (unsigned i = 0; i < sizeof DECO_SEG / sizeof *DECO_SEG; i++)\n")
    w.write("        memcpy(image_base + DECO_SEG[i].rva, DECO_BLOB + DECO_SEG[i].off, DECO_SEG[i].len);\n")
    w.write("}\n")

print(f"[*] wrote {OUT}: {len(blob)} bytes across {len(descr)} segments "
      f"({', '.join(hex(d[0]) for d in descr)}); image base {hex(base)} size {hex(imgsz)}")
