/* AUTO-GENERATED by lift.py - do not edit */
#include "cpu.h"

void L_11019780(CPU *c)
{
    push32(c, c->ebx);                                           /* 11019780: push ebx */
    c->edx = (uint32_t)(flags_logicz(c, c->edx ^ c->edx, 4));    /* 11019781: xor edx, edx */
    push32(c, c->esi);                                           /* 11019783: push esi */
    push32(c, c->edi);                                           /* 11019784: push edi */
    push32(c, c->ebp);                                           /* 11019785: push ebp */
    c->esi = (uint32_t)(c->ecx);                                 /* 11019786: mov esi, ecx */
L_11019788:
    c->edi = (uint32_t)(rd32((c->esi + 0x0000003Cu)));           /* 11019788: mov edi, dword ptr [esi + 0x3c] */
    c->ecx = (uint32_t)(rd32((c->esi + 0x00000040u)));           /* 1101978B: mov ecx, dword ptr [esi + 0x40] */
    c->eax = (uint32_t)(flags_logicz(c, c->eax ^ c->eax, 4));    /* 1101978E: xor eax, eax */
    SET8L(c->ebx, rd8((c->edi)));                                /* 11019790: mov bl, byte ptr [edi] */
    SET8L(c->ebx, op_shr(c, R8L(c->ebx), R8L(c->ecx), 1));       /* 11019792: shr bl, cl */
    SET8L(c->ebx, flags_logicz(c, R8L(c->ebx) & 0x1u, 1));       /* 11019794: and bl, 1 */
    c->ecx = (uint32_t)(flags_incs(c, c->ecx, 4));               /* 11019797: inc ecx */
    SET8L(c->eax, R8L(c->ebx));                                  /* 11019798: mov al, bl */
    wr32((c->esi + 0x00000040u), c->ecx);                        /* 1101979A: mov dword ptr [esi + 0x40], ecx */
    flags_sub(c, c->ecx, 0x7u, 4);                               /* 1101979D: cmp ecx, 7 */
    if ((c->cf || c->zf)) goto L_110197AD;                       /* 110197A0: jbe 0x110197ad */
    wr32((c->esi + 0x00000040u), 0x0u);                          /* 110197A2: mov dword ptr [esi + 0x40], 0 */
    c->edi = (uint32_t)(flags_incs(c, c->edi, 4));               /* 110197A9: inc edi */
    wr32((c->esi + 0x0000003Cu), c->edi);                        /* 110197AA: mov dword ptr [esi + 0x3c], edi */
L_110197AD:
    flags_sub(c, c->eax, 0x1u, 4);                               /* 110197AD: cmp eax, 1 */
    if (!c->zf) goto L_110197B5;                                 /* 110197B0: jne 0x110197b5 */
    c->edx = (uint32_t)(flags_incs(c, c->edx, 4));               /* 110197B2: inc edx */
    goto L_11019788;                                             /* 110197B3: jmp 0x11019788 */
L_110197B5:
    flags_logicz(c, c->edx & c->edx, 4);                         /* 110197B5: test edx, edx */
    if (!c->zf) goto L_110197C3;                                 /* 110197B7: jne 0x110197c3 */
    c->eax = (uint32_t)(0x1u);                                   /* 110197B9: mov eax, 1 */
    c->ebp = (uint32_t)(pop32(c));                               /* 110197BE: pop ebp */
    c->edi = (uint32_t)(pop32(c));                               /* 110197BF: pop edi */
    c->esi = (uint32_t)(pop32(c));                               /* 110197C0: pop esi */
    c->ebx = (uint32_t)(pop32(c));                               /* 110197C1: pop ebx */
    c->esp += 4; return;                                         /* 110197C2: ret  */
L_110197C3:
    c->edx = (uint32_t)(flags_decs(c, c->edx, 4));               /* 110197C3: dec edx */
    c->ebx = (uint32_t)(rd32((c->esi + 0x0000003Cu)));           /* 110197C4: mov ebx, dword ptr [esi + 0x3c] */
    c->eax = (uint32_t)((R16(c->edx)));                          /* 110197C7: movzx eax, dx */
    c->ecx = (uint32_t)(rd32((c->esi + 0x00000040u)));           /* 110197CA: mov ecx, dword ptr [esi + 0x40] */
    c->ebp = (uint32_t)(rd32((c->ebx)));                         /* 110197CD: mov ebp, dword ptr [ebx] */
    c->ebp = (uint32_t)(op_shr(c, c->ebp, R8L(c->ecx), 4));      /* 110197CF: shr ebp, cl */
    c->edi = (uint32_t)(rd32((c->eax*4 + GVA(0x11020428))));     /* 110197D1: mov edi, dword ptr [eax*4 + 0x11020428] */
    c->eax = (uint32_t)(flags_add(c, c->eax, c->ecx, 4));        /* 110197D8: add eax, ecx */
    c->edi = (uint32_t)(flags_logicz(c, c->edi & c->ebp, 4));    /* 110197DA: and edi, ebp */
    c->ecx = (uint32_t)(c->eax);                                 /* 110197DC: mov ecx, eax */
    c->ecx = (uint32_t)(op_shr(c, c->ecx, 0x3u, 4));             /* 110197DE: shr ecx, 3 */
    wr32((c->esi + 0x00000040u), c->eax);                        /* 110197E1: mov dword ptr [esi + 0x40], eax */
    c->ecx = (uint32_t)(flags_add(c, c->ecx, c->ebx, 4));        /* 110197E4: add ecx, ebx */
    c->eax = (uint32_t)(flags_logicz(c, c->eax & 0x7u, 4));      /* 110197E6: and eax, 7 */
    wr32((c->esi + 0x0000003Cu), c->ecx);                        /* 110197E9: mov dword ptr [esi + 0x3c], ecx */
    wr32((c->esi + 0x00000040u), c->eax);                        /* 110197EC: mov dword ptr [esi + 0x40], eax */
    c->eax = (uint32_t)(0x1u);                                   /* 110197EF: mov eax, 1 */
    SET8L(c->ecx, R8L(c->edx));                                  /* 110197F4: mov cl, dl */
    c->eax = (uint32_t)(op_shl(c, c->eax, R8L(c->ecx), 4));      /* 110197F6: shl eax, cl */
    c->eax = (uint32_t)(flags_logicz(c, c->eax | c->edi, 4));    /* 110197F8: or eax, edi */
    c->ebp = (uint32_t)(pop32(c));                               /* 110197FA: pop ebp */
    c->eax = (uint32_t)(flags_incs(c, c->eax, 4));               /* 110197FB: inc eax */
    c->edi = (uint32_t)(pop32(c));                               /* 110197FC: pop edi */
    c->esi = (uint32_t)(pop32(c));                               /* 110197FD: pop esi */
    c->ebx = (uint32_t)(pop32(c));                               /* 110197FE: pop ebx */
    c->esp += 4; return;                                         /* 110197FF: ret  */
}
